#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG="install.conf"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
PACAUR_BIN="${BASEDIR}/dotbot-pacaur/pacaur.py"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" -p "${PACAUR_BIN}" "${@}"
